// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RenderUIClient is the client API for RenderUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RenderUIClient interface {
	// ListEngineSpecs returns a list of Render Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RenderUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type renderUIClient struct {
	cc grpc.ClientConnInterface
}

func NewRenderUIClient(cc grpc.ClientConnInterface) RenderUIClient {
	return &renderUIClient{cc}
}

func (c *renderUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RenderUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RenderUI_ServiceDesc.Streams[0], "/v1.RenderUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &renderUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RenderUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type renderUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *renderUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *renderUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.RenderUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RenderUIServer is the server API for RenderUI service.
// All implementations must embed UnimplementedRenderUIServer
// for forward compatibility
type RenderUIServer interface {
	// ListEngineSpecs returns a list of Render Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, RenderUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedRenderUIServer()
}

// UnimplementedRenderUIServer must be embedded to have forward compatible implementations.
type UnimplementedRenderUIServer struct {
}

func (UnimplementedRenderUIServer) ListEngineSpecs(*ListEngineSpecsRequest, RenderUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedRenderUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedRenderUIServer) mustEmbedUnimplementedRenderUIServer() {}

// UnsafeRenderUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RenderUIServer will
// result in compilation errors.
type UnsafeRenderUIServer interface {
	mustEmbedUnimplementedRenderUIServer()
}

func RegisterRenderUIServer(s grpc.ServiceRegistrar, srv RenderUIServer) {
	s.RegisterService(&RenderUI_ServiceDesc, srv)
}

func _RenderUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RenderUIServer).ListEngineSpecs(m, &renderUIListEngineSpecsServer{stream})
}

type RenderUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type renderUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *renderUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RenderUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenderUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.RenderUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenderUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RenderUI_ServiceDesc is the grpc.ServiceDesc for RenderUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RenderUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RenderUI",
	HandlerType: (*RenderUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _RenderUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _RenderUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "render-ui.proto",
}
