
// Code generated by Bhojpur Render - 3D Graphics Engine ('renderglapi') and contains declarations
// of public functions from "glapli.c".

#ifndef _glapi_h_
#define _glapi_h_

#include "glcorearb.h"

// Loads the OpenGL function pointers
int glapiLoad(void);

// Set the internal flag to enable/disable OpenGL error checking
void glapiCheckError(int check);

#endif
