// Code generated by "stringer -type=Dims"; DO NOT EDIT.

package math32

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[X-0]
	_ = x[Y-1]
	_ = x[Z-2]
	_ = x[W-3]
	_ = x[DimsN-4]
}

const _Dims_name = "XYZWDimsN"

var _Dims_index = [...]uint8{0, 1, 2, 3, 4, 9}

func (i Dims) String() string {
	if i < 0 || i >= Dims(len(_Dims_index)-1) {
		return "Dims(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Dims_name[_Dims_index[i]:_Dims_index[i+1]]
}
